default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PG_DEV_USERNAME"] %>
  password: <%= ENV["PG_DEV_PASSWORD"] %>
  host: localhost

development:
  <<: *default
  database: ror_blog_app_development

test:
  <<: *default
  database: ror_blog_app_test
